stages:
  - obs

variables:
  BUILD_IMAGES_PROJECT: azure-li/azure-li-ci-containers
  TUMBLEWEED_BUILD: buildenv-tumbleweed

update_obs_services:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$TUMBLEWEED_BUILD
  stage: obs
  only:
    - master
  except:
    - schedules
  script:
    - base64 --decode "$HOP_HOST_SECRET" > id_hop_host
    - chmod 600 id_hop_host
    - ssh -o StrictHostKeyChecking=no -i id_hop_host $(echo "$HOP_HOST" | base64 --decode) 2>/dev/null

mirror_testing_images:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$TUMBLEWEED_BUILD
  stage: obs
  only:
    - schedules
  script:
    - base64 --decode "$HOP_HOST_SECRET_AZURE_TESTING" > id_hop_host
    - chmod 600 id_hop_host
    - ssh -o StrictHostKeyChecking=no -i id_hop_host $(echo "$HOP_HOST" | base64 --decode) 2>/dev/null

create_obs_static_data:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$TUMBLEWEED_BUILD
  stage: obs
  only:
    - master
  except:
    - schedules
  script:
    - ./obs_static.sh
  artifacts:
    paths:
      - obs
